version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  compile:
    executor:
      name: node/default
      tag: '16.13'
    steps:
      - checkout
      - node/install-packages
      - run: npm run compile
      - persist_to_workspace:
          root: .
          paths:
            - .

  coverage:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run compile
      - run: npm run test:coverage
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    executor:
      name: node/default
      tag: '16.13'
    steps:
      - checkout
      # Install the latest npm - the node Orb takes care of it
      # - node/install-npm
      # Install dependencies - the node Orb take care of installation and dependency caching
      - node/install-packages:
          cache-path: node_modules
          override-ci-command: npm ci
      - run: npm run lint
      # Save workspace for subsequent jobs
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor:
      name: node/default
      tag: '16.13'
    steps:
      - checkout
      - node/install-packages
      - run: npm run compile
      - run: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - compile:
          requires:
            - lint
      - test:
          requires:
            - compile
      - coverage:
          requires:
            - test
