version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
  node: circleci/node@1.1.6

workflows:
  build-test-report:
    jobs:
      - checkout-and-install
      - compile-and-test:
          requires:
            - checkout-and-install

jobs:
  checkout-and-install:
    working_directory: ~/templates
    docker:
      - image: circleci/node:10.18.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - save_cache:
          key: templates-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/templates

  compile-and-test:
    working_directory: ~/templates
    docker:
      - image: circleci/node:10.18.0
    steps:
      - checkout
      - restore_cache:
          key: templates-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Compile Contracts
          command: npx hardhat compile
      - run:
          name: Unit Test 
          command: npm run test
      # - run:
      #     name: Mainnet fork test
      #     command: npm run test:fork

      